### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by charlieporth1** [cloud-unpacked/tmhi#7]
When running this command I get 
`tmhi signal`
On MacOS 

<img width="316" alt="image" src="https://github.com/cloud-unpacked/tmhi/assets/13573364/3628603c-994c-4c5d-aff6-2f816c2a4179">

```
tmhi signal 
4G Signal:
Bars: ▯▯▯▯▯ (0/5)
RSRQ: great (0)
SINR: poor (0)
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/cloud-unpacked/tmhi/tmhi/cmd.displaySignalData({{0x0, 0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}, {0x1491102, 0x2})
        /home/circleci/project/tmhi/cmd/signal.go:106 +0x572
github.com/cloud-unpacked/tmhi/tmhi/cmd.glob..func5(0x17d6320?, {0x1491719?, 0x0?, 0x0?})
        /home/circleci/project/tmhi/cmd/signal.go:42 +0x2ec
github.com/spf13/cobra.(*Command).execute(0x17d6320, {0x180fa48, 0x0, 0x0})
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x17d5ba0)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/circleci/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/cloud-unpacked/tmhi/tmhi/cmd.Execute()
        /home/circleci/project/tmhi/cmd/root.go:29 +0x25
main.main()
        /home/circleci/project/tmhi/main.go:6 +0x17
```

**Comment by FelicianoTech** [comment]
Thank you for reporting. I'll look into this.

**Comment by charlieporth1** [comment]
Im running a Nokia fastmile so I don't think this software is compatible

**Comment by FelicianoTech** [comment]
No. If it's not one of the three gateways T-Mobile provides.

**Comment by charlieporth1** [comment]
Nokia fast mile is one of the ones T-Mobile provides. but it uses a different api
